### ISSUE TITLE
Registry fails to create cache directory when missing

### ISSUE THREAD

**Issue by at88mph** [opencadc/reg#19]
For clean deployments, the cache directory is missing, but should be created on the fly.  However, the system fails to do so, even though it can write to the destination folder:

```
Mar 15, 2017 2:15:57 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() ...
java.lang.RuntimeException: Failed to create directory: ${catalina.temp.home}/servops/cadc-registry/alt-domains/MYHOST
	at ca.nrc.cadc.reg.client.CachingFile.checkCacheDirectory(CachingFile.java:192)
	at ca.nrc.cadc.reg.client.CachingFile.<init>(CachingFile.java:148)
	at ca.nrc.cadc.reg.client.CachingFile.<init>(CachingFile.java:130)
	at ca.nrc.cadc.reg.client.RegistryClient.getCapabilities(RegistryClient.java:260)
	at ca.nrc.cadc.reg.client.RegistryClient.getServiceURL(RegistryClient.java:326)
	...
```

Creating the path manually works around this issue.

**Comment by brianmajor** [comment]
Dustin, does  ${catalina.temp.home} exist?  If not, it should fail.

**Comment by at88mph** [comment]
Yes, it exists.  I just replaced my actual path with an environment variable to omit unnecessary details.  On my system, that's `/var/home/servops/tomcat-ui/temp`.

Even within a Docker container, which is running as root, fails to create the path.

**Comment by brianmajor** [comment]
Okay, that's a bug I guess.  I don't know why it's never happened to me.
I've cleared that directory and it recreates the entire structure.

Brian
